version: '3.1'

services:
  mongo:
    image: mongo:5

  api:
    build: ./backend/
    ports:
      - 3000:3000
    environment:
      MONGODB_URL: mongodb://mongo:27017/

  frontend:
    build: ./frontend/
    ports:
      - 8080:80
